# Generated by Django 4.0.5 on 2022-06-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todomodel_completed_alter_todomodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='completed',
            field=models.CharField(max_length=70),
        ),
    ]
